// Autogenerated by Thrift Compiler (0.11.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "recommend"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  string test(string word)")
  fmt.Fprintln(os.Stderr, "  Response recommend(Request req)")
  fmt.Fprintln(os.Stderr, "   fetchTabs(Request req)")
  fmt.Fprintln(os.Stderr, "   fetchBannerData(Request req)")
  fmt.Fprintln(os.Stderr, "   getDetails(DIRequest req)")
  fmt.Fprintln(os.Stderr, "   getGenresList(Request req)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := recommend.NewRecommendServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "test":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "Test requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.Test(context.Background(), value0))
    fmt.Print("\n")
    break
  case "recommend":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "Recommend requires 1 args")
      flag.Usage()
    }
    arg43 := flag.Arg(1)
    mbTrans44 := thrift.NewTMemoryBufferLen(len(arg43))
    defer mbTrans44.Close()
    _, err45 := mbTrans44.WriteString(arg43)
    if err45 != nil {
      Usage()
      return
    }
    factory46 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt47 := factory46.GetProtocol(mbTrans44)
    argvalue0 := recommend.NewRequest()
    err48 := argvalue0.Read(jsProt47)
    if err48 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.Recommend(context.Background(), value0))
    fmt.Print("\n")
    break
  case "fetchTabs":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "FetchTabs requires 1 args")
      flag.Usage()
    }
    arg49 := flag.Arg(1)
    mbTrans50 := thrift.NewTMemoryBufferLen(len(arg49))
    defer mbTrans50.Close()
    _, err51 := mbTrans50.WriteString(arg49)
    if err51 != nil {
      Usage()
      return
    }
    factory52 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt53 := factory52.GetProtocol(mbTrans50)
    argvalue0 := recommend.NewRequest()
    err54 := argvalue0.Read(jsProt53)
    if err54 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.FetchTabs(context.Background(), value0))
    fmt.Print("\n")
    break
  case "fetchBannerData":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "FetchBannerData requires 1 args")
      flag.Usage()
    }
    arg55 := flag.Arg(1)
    mbTrans56 := thrift.NewTMemoryBufferLen(len(arg55))
    defer mbTrans56.Close()
    _, err57 := mbTrans56.WriteString(arg55)
    if err57 != nil {
      Usage()
      return
    }
    factory58 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt59 := factory58.GetProtocol(mbTrans56)
    argvalue0 := recommend.NewRequest()
    err60 := argvalue0.Read(jsProt59)
    if err60 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.FetchBannerData(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getDetails":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetDetails requires 1 args")
      flag.Usage()
    }
    arg61 := flag.Arg(1)
    mbTrans62 := thrift.NewTMemoryBufferLen(len(arg61))
    defer mbTrans62.Close()
    _, err63 := mbTrans62.WriteString(arg61)
    if err63 != nil {
      Usage()
      return
    }
    factory64 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt65 := factory64.GetProtocol(mbTrans62)
    argvalue0 := recommend.NewDIRequest()
    err66 := argvalue0.Read(jsProt65)
    if err66 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetDetails(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getGenresList":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetGenresList requires 1 args")
      flag.Usage()
    }
    arg67 := flag.Arg(1)
    mbTrans68 := thrift.NewTMemoryBufferLen(len(arg67))
    defer mbTrans68.Close()
    _, err69 := mbTrans68.WriteString(arg67)
    if err69 != nil {
      Usage()
      return
    }
    factory70 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt71 := factory70.GetProtocol(mbTrans68)
    argvalue0 := recommend.NewRequest()
    err72 := argvalue0.Read(jsProt71)
    if err72 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetGenresList(context.Background(), value0))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
